version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my-todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwe123Rty456
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: my-todo-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Qwe123Rty456@db:5432/todo_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: my-todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - EXPO_PACKAGER_PROXY_URL=http://backend:8000
    stdin_open: true
    tty: true

volumes:
  postgres_data: